### ISSUE TITLE
Integrate Semgrep to CI

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#1736]
### Description

Lisk Service uses various data validation schemas using regex. Sometimes, the validation patterns are hard-coded and duplicated at various places. To avoid unnecessary maintenance overheads, such situations must be identified as early as possible. One way to achieve the same would be to integrate code analysis to the CI.

### Acceptance Criteria

- Integrate Semgrep to the CI pipeline
- Add relevant Semgrep rules to enable such static code validations

### Additional Information
- Use the following rule to setup the hardcoded pattern validations for the microservice method definitions
```yml
rules:
  - id: schema_hardcoded_pattern
    message: A fastest-validator schema uses a hardcoded pattern instead of a
constant
    languages: [javascript]
    severity: WARNING
    patterns:
      - pattern-inside: >
          {
            params: {
              $X: { pattern: /.../ },
            }
          }
```
- The following public rulesets must be executed
  - p/javascript
  - p/r2c
  - p/r2c-security-audit
  - p/r2c-best-practices
  - p/nodejs
  - p/nodejsscan
